from numba import njit
import numpy as np
import glm
import math
import time

# OpenGL settings
MAJOR_VER, MINOR_VER = 3, 3
DEPTH_SIZE = 24
NUM_SAMPLES = 1  # antialiasing

WIN_RESOLUTION = glm.vec2(1920, 1080)

# world generation
SEED = int(time.time())
print("WORLD SEED:", SEED)

# raycasting
MAX_RAY_DIST = 7

# chunk
CHUNK_SIZE = 48
H_CHUNK_SIZE = CHUNK_SIZE // 2
CHUNK_AREA = CHUNK_SIZE * CHUNK_SIZE
CHUNK_VOL = CHUNK_AREA * CHUNK_SIZE
CHUNK_SPHERE_RADIUS = H_CHUNK_SIZE * math.sqrt(3)

# world
WORLD_W, WORLD_H = 32, 4
WORLD_D = WORLD_W
WORLD_AREA = WORLD_W * WORLD_D
WORLD_VOL = WORLD_AREA * WORLD_H

# world center
CENTER_XZ = WORLD_W * H_CHUNK_SIZE
CENTER_Y = WORLD_H * H_CHUNK_SIZE 

# camera
ASPECT_RATIO = WIN_RESOLUTION.x / WIN_RESOLUTION.y
FOG_DEG = 90
V_FOV = glm.radians(FOG_DEG) # vertical fov
H_FOV = 2 * math.atan(math.tan(V_FOV * 0.5) * ASPECT_RATIO) # horizontal fov
NEAR = 0.1
FAR = 2000.0
PITCH_MAX = glm.radians(89)

# player
PLAYER_SPEED = 0.02 # 0.0008
PLAYER_ROT_SPEED = 0.004
PLAYER_POS = glm.vec3(CENTER_XZ, WORLD_H * CHUNK_SIZE, CENTER_XZ)
MOUSE_SENSITIVITY = 0.002

BG_COLOR = glm.vec3(0.72, 0.88, 1.0)

# textures
SAND = 1
GRASS = 2
DIRT = 3
STONE = 4
SNOW = 5
LEAVES = 6
WOOD = 7

# terrain levels
SNOW_LEVEL = 54
STONE_LEVEL = 48
DIRT_LEVEL = 44
GRASS_LEVEL = 8
SAND_LEVEL = 4

# tree settings
TREE_PROBABILITY = 0.008
TREE_WIDTH, TREE_HEIGHT = 5, 9
TREE_H_WIDTH, TREE_H_HEIGHT = TREE_WIDTH // 2, TREE_HEIGHT // 2

# spruce settings
SPRUCE_PROBABILITY = 0.025
SPRUCE_MIN_HEIGHT = 11
SPRUCE_MAX_HEIGHT = 17
SPRUCE_MAX_RADIUS = 4

# water
WATER_LINE = 5.6
WATER_AREA = 5 * CHUNK_SIZE * WORLD_W

# cloud
CLOUD_SCALE = 25
CLOUD_HEIGHT = WORLD_H * CHUNK_SIZE * 2